person:
  id: 2
  name: 张三
  hobby:
    - play
    - read
    - sleep
  family: [ father, mother ]
  map: { k1: v1, k2: v2 }
  pet: { type: dot, name: Tom }
#  map:
#    k1: v1
#    k2: v2
spring:
  profiles:
    active: dev